### ISSUE TITLE
I am facing an error in this project, i have installed python 3.8 and also successfully install those three modules but it is showing erros, the errors are in the description

### ISSUE THREAD

**Issue by Cleavermind110** [HxnDev/Virtual-Mouse-using-OpenCV#1]
"E:\Virtual-Mouse-using-OpenCV-main>python "Virtual Mouse.py"
Traceback (most recent call last):
  File "Virtual Mouse.py", line 1, in <module>
    import cv2
  File "E:\Python\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "E:\Python\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "E:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be f"

**Comment by katyalmohit** [comment]
Can you provide the code snippet?
